name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  lint_and_test:
    runs-on: ubuntu-20.04
    environment: testing

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
        

      - name: Install dependencies (root)
        run: npm install

      - name: Run ESLint (root)
        run: npm run eslint

      - name: Install dependencies (frontend)
        working-directory: ./frontend
        run: npm install
        
      - name: Run ESLint (frontend)
        working-directory: ./frontend
        run: npm run eslint

      - name: Run Vitest
        working-directory: ./frontend
        run: npm run test

      - name: Run Supertest
        run: npm run test
        env:
          TEST_MONGODB_URI: ${{ secrets.MONGODB_URI}}

      - name: Frontend Build
        run: npm run build:ui
        
      - name: Run e2e Test
        run: npm run test:e2e
        env:
          TEST_MONGODB_URI: ${{ secrets.MONGODB_URI}}


  # deploy_prod:
  #   needs: 
  #     - deployment_pipeline
  #   runs-on: ubuntu:latest
  #   steps:
  #     - name: prod deploy
  #       run: | 
  #         echo "prod deploy placeholder"

